### ISSUE TITLE
Invisible Highlights

### ISSUE THREAD

**Issue by vaovidiu** [JosNun/night-mode-bible#1]
Hi,

Great theme, very useful when you want to read off a screen for longer.
There's just one thing: the highlights are essentially unreadable -- see image. I have to turn it off every time I come across one of my highlights - when their very purpose is to jump at me.

I wonder if it's even possible that the extension detect such cases and automatically adjust style for those?
Thank you,

![image](https://user-images.githubusercontent.com/9292337/82789111-6f5c4600-9e72-11ea-9ac9-afc778ed2270.png)

**Comment by JosNun** [comment]
Apologies for letting this linger so long. Can you confirm that you still have the issue? I believe it should be fixed, but would like to confirm.

**Comment by vaovidiu** [comment]
Yeap, I can confirm that the issue is fixed. Thank you!!!
(sorry, just now I noticed the 'closed' status, but have failed to notice your question from much earlier)

**Comment by JosNun** [comment]
All good, thanks!
