### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by dadodasyra** [JosNun/night-mode-bible#2]
The new theme broke some things in the extension like the footer

**Comment by JosNun** [comment]
Unfortunately, I've not had time to work on this recently, as my other commitments have been using up my time. I'd be more than happy to accept any pull requests, if someone were to open one, though!

**Comment by JosNun** [comment]
Just did a quick update to address a couple O the more egregious issues. Let me know if there's any other major issues that you stumble upon!
