### ISSUE TITLE
Dark Text  Dark background

### ISSUE THREAD

**Issue by saltymedic** [JosNun/night-mode-bible#3]
Here is a place where the text is dark and the background is dark. It is on the listing for the readings in a plan for the day. 

Any chance you can fix that please? Thank you for making this. Reading my Bible in the morning with the dark background is much easier on my eyes.

![Selection_072](https://github.com/JosNun/night-mode-bible/assets/18824694/12a0011c-d669-4abb-b639-8e3bfff7866f)

**Comment by JosNun** [comment]
I appreciate you opening an issue! I'm not sure when I'll get to it, but I'll add that to my list of things to fix. Thanks!

**Comment by JosNun** [comment]
Fix submitted to the Chrome Web store, so it'll be fixed when it's been reviewed. Closing this issue for now. Thanks again for the report!
