### ISSUE TITLE
White Bar Glitch 

### ISSUE THREAD

**Issue by Michael158037** [JosNun/night-mode-bible#4]
There is an annoying white bar at the top where the search bar is and I don't know why this is happening. Please Help! thank you 
[](url)
<img width="1352" alt="Screenshot 2024-04-03 at 9 43 13 AM" src="https://github.com/JosNun/night-mode-bible/assets/165934990/30469437-8dfd-4cab-ab8c-9445b0ccef4c">

**Comment by JosNun** [comment]
Hey @Michael158037 thanks for opening the issue! I'll add it to my todo list of items to work on, but can't guarantee a quick fix, due to scheduling. Thanks again for reporting this!

**Comment by Michael158037** [comment]
@JosNun Take your time! I appreciate the reply and will eagerly await.

**Comment by JosNun** [comment]
Hey @Michael158037, just submitted an update to Google for review, after which, it should be live. I'm gonna go ahead and close this issue. The report was much-appreciated!
